name: Master build
on: [push]
jobs:
  run-tox-tests:
      runs-on: windows-latest
      strategy:
        matrix:
          python: [3.6, 3.7, 3.8, 3.9]
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python }}
        - name: Install tox
          run: pip install tox
        - name: Run Tox
          run: tox -e py
  run-tox-linting:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install tox
        run: pip install tox
      - name: Run linting
        run: tox -e linting
      - name: Run coverage
        run: tox -e coverage